-- Presenter session ownership for Pulse.
-- Run this once in Supabase Dashboard → SQL Editor.
create table if not exists public.presenter_sessions (
  code text primary key check (code ~ '^[0-9]{6}$'),
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists presenter_sessions_owner_idx
  on public.presenter_sessions(owner_id, created_at desc);

alter table public.presenter_sessions enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.presenter_sessions to authenticated;

drop policy if exists "Presenters can read their own sessions" on public.presenter_sessions;
create policy "Presenters can read their own sessions"
  on public.presenter_sessions for select
  using (auth.uid() = owner_id);

drop policy if exists "Presenters can create their own sessions" on public.presenter_sessions;
create policy "Presenters can create their own sessions"
  on public.presenter_sessions for insert
  with check (auth.uid() = owner_id);

-- Pulse data now lives in Supabase. Google Sheets is no longer required.
create table if not exists public.rooms (
  code text primary key check (code ~ '^[0-9]{6}$'),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Untitled live session',
  active_question bigint not null default 0,
  ended integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  type text not null check (type = 'open'),
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  position integer not null default 0
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  participant_id text not null,
  display_name text not null default 'Anonymous participant',
  answer text not null,
  created_at timestamptz not null default now()
);

create index if not exists rooms_owner_idx on public.rooms(owner_id, created_at desc);
create index if not exists questions_room_idx on public.questions(room_code, position);
create index if not exists responses_room_idx on public.responses(room_code, question_id);

alter table public.rooms enable row level security;
alter table public.questions enable row level security;
alter table public.responses enable row level security;

grant select on table public.rooms, public.questions, public.responses to anon, authenticated;
grant insert, update on table public.rooms, public.questions to authenticated;
grant insert on table public.responses to anon, authenticated;

drop policy if exists "Anyone can read rooms" on public.rooms;
create policy "Anyone can read rooms" on public.rooms for select using (true);
drop policy if exists "Presenters can create rooms" on public.rooms;
create policy "Presenters can create rooms" on public.rooms for insert to authenticated with check (auth.uid() = owner_id);
drop policy if exists "Presenters can update their rooms" on public.rooms;
create policy "Presenters can update their rooms" on public.rooms for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Anyone can read questions" on public.questions;
create policy "Anyone can read questions" on public.questions for select using (true);
drop policy if exists "Presenters can create questions in their rooms" on public.questions;
create policy "Presenters can create questions in their rooms" on public.questions for insert to authenticated
  with check (exists (select 1 from public.rooms owned_room where owned_room.code = public.questions.room_code and owned_room.owner_id = auth.uid()));

drop policy if exists "Anyone can read responses" on public.responses;
create policy "Anyone can read responses" on public.responses for select using (true);
drop policy if exists "Participants can submit responses" on public.responses;
create policy "Participants can submit responses" on public.responses for insert to anon, authenticated with check (true);
